export const nativeResetRoot: string;
export const root: string;
export const pressed: string;
export const disabled: string;
export const defaultKind: string;
export const secondaryKind: string;
export const icon: string;
export const iconOnly: string;
export const label: string;
