export const root: string;
export const open: string;
export const main: string;
export const title: string;
export const content: string;
export const close: string;
export const closeIcon: string;
export const underlayVisible: string;
export const actions: string;
