export const root: string;
export const sticky: string;
export const row: string;
export const primary: string;
export const secondary: string;
export const leading: string;
export const title: string;
export const action: string;
export const trailing: string;
