export const root: string;
export const up: string;
export const actions: string;
export const action: string;
export const down: string;
export const left: string;
export const right: string;
export const open: string;
export const actionTransition: string;
