const states = [
	{ value: 'Alabama' },
	{ value: 'Alaska' },
	{ value: 'Arizona', disabled: true },
	{ value: 'Arkansas' },
	{ value: 'California' },
	{ value: 'Colorado' },
	{ value: 'Connecticut' },
	{ value: 'Delaware' },
	{ value: 'Florida' },
	{ value: 'Georgia', disabled: true },
	{ value: 'Hawaii' },
	{ value: 'Idaho' },
	{ value: 'Illinois' },
	{ value: 'Indiana' },
	{ value: 'Iowa' },
	{ value: 'Kansas' },
	{ value: 'Kentucky' },
	{ value: 'Louisiana', disabled: true },
	{ value: 'Maine' },
	{ value: 'Maryland' },
	{ value: 'Massachusetts' },
	{ value: 'Michigan' },
	{ value: 'Minnesota', disabled: true },
	{ value: 'Mississippi' },
	{ value: 'Missouri' },
	{ value: 'Montana' },
	{ value: 'Nebraska' },
	{ value: 'Nevada' },
	{ value: 'New Hampshire' },
	{ value: 'New Jersey' },
	{ value: 'New Mexico' },
	{ value: 'New York' },
	{ value: 'North Carolina' },
	{ value: 'North Dakota', disabled: true },
	{ value: 'Ohio' },
	{ value: 'Oklahoma', disabled: true },
	{ value: 'Oregon' },
	{ value: 'Pennsylvania' },
	{ value: 'Rhode Island' },
	{ value: 'South Carolina' },
	{ value: 'South Dakota' },
	{ value: 'Tennessee' },
	{ value: 'Texas' },
	{ value: 'Utah' },
	{ value: 'Vermont' },
	{ value: 'Virginia' },
	{ value: 'Washington' },
	{ value: 'West Virginia', disabled: true },
	{ value: 'Wisconsin' },
	{ value: 'Wyoming' }
];

export default states;
