export const root: string;
export const linksWrapper: string;
export const prev: string;
export const next: string;
export const icon: string;
export const label: string;
export const link: string;
export const currentPage: string;
export const selectWrapper: string;
