export const root: string;
export const input: string;
export const defaultKind: string;
export const outlinedKind: string;
export const disabled: string;
export const readonly: string;
export const invalid: string;
export const valid: string;
export const notchedOutlineNotch: string;
