export const root: string;
export const underlay: string;
export const underlayVisible: string;
export const content: string;
export const left: string;
export const right: string;
export const open: string;
export const slideOut: string;
export const slideIn: string;
