export const root: string;
export const slideIn: string;
export const slideOut: string;
export const underlayVisible: string;
export const content: string;
export const open: string;
export const pane: string;
export const title: string;
export const close: string;
