import '../../../button/tests/functional/Button';
import '../../../calendar/tests/functional/Calendar';
import '../../../checkbox/tests/functional/Checkbox';
import '../../../combobox/tests/functional/ComboBox';
import '../../../radio/tests/functional/Radio';
import '../../../slidepane/tests/functional/SlidePane';
import '../../../tabpane/tests/functional/TabPane';
import '../../../textinput/tests/functional/TextInput';
import '../../../titlepane/tests/functional/TitlePane';
