export const addon: string;
export const addonAfter: string;
export const addonBefore: string;
export const input: string;
export const invalid: string;
export const helperTextWrapper: string;
export const helperText: string;
export const inputWrapper: string;
export const inputWrapperInner: string;
