export const root: string;
export const content: string;
export const label: string;
export const actions: string;
export const open: string;
export const success: string;
export const error: string;
export const leading: string;
export const stacked: string;
