export const root: string;
export const clearable: string;
export const controls: string;
export const dropdown: string;
export const clear: string;
export const trigger: string;
export const valid: string;
export const invalid: string;
export const open: string;
