export const root: string;
export const label: string;
export const inputWrapper: string;
export const arrow: string;
export const disabled: string;
export const readonly: string;
export const invalid: string;
export const valid: string;
export const required: string;
