export const root: string;
export const text: string;
export const contained: string;
export const outlined: string;
export const popup: string;
export const disabled: string;
export const icon: string;
export const iconOnly: string;
export const label: string;
