export const root: string;
export const disabled: string;
export const fileItem: string;
export const invalid: string;
export const fileInfo: string;
export const fileItemName: string;
export const fileItemSize: string;
export const closeButton: string;
export const validationMessage: string;
