export const root: string;
export const pagination: string;
export const details: string;
export const paginationList: string;
export const item: string;
export const more: string;
export const pageNumber: string;
export const pageNav: string;
export const active: string;
