export const root: string;
export const readonly: string;
export const invalid: string;
export const valid: string;
export const required: string;
export const disabled: string;
export const focused: string;
export const secondary: string;
export const active: string;
