export const root: string;
export const node: string;
export const contentWrapper: string;
export const content: string;
export const leaf: string;
export const selectable: string;
export const selected: string;
export const expander: string;
export const title: string;
